// Date: 2016/05/07 19:35:21
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package mods.hinasch.unsaga.core.client.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelRuffleTree extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Spore1;
    ModelRenderer Spore2;
    ModelRenderer Spore3;
    ModelRenderer Spore4;

  public ModelRuffleTree()
  {
    textureWidth = 64;
    textureHeight = 32;

      Shape1 = new ModelRenderer(this, -32, 0);
      Shape1.addBox(-8F, 0F, -8F, 16, 0, 16);
      Shape1.setRotationPoint(0F, 23.22222F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 16);
      Shape2.addBox(-1.666667F, 1F, -2F, 3, 8, 4);
      Shape2.setRotationPoint(-1F, 16F, 0F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0.069046F, 0.103569F, -0.34523F);
      Shape3 = new ModelRenderer(this, 0, 16);
      Shape3.addBox(-1F, -0.6F, -1.133333F, 2, 7, 2);
      Shape3.setRotationPoint(-1F, 11F, 0F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 14, 16);
      Shape4.addBox(-1F, 0F, -3F, 2, 8, 8);
      Shape4.setRotationPoint(-3F, 3F, 0F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, -0.034523F, 0.7249829F, -0.241661F);
      Shape5 = new ModelRenderer(this, 16, -3);
      Shape5.addBox(0F, 0F, -1.4F, 0, 3, 3);
      Shape5.setRotationPoint(-4F, 21F, -5F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0.9325045F, 0F);
      Spore1 = new ModelRenderer(this, 16, 3);
      Spore1.addBox(-1F, -1F, -1F, 2, 2, 2);
      Spore1.setRotationPoint(-4F, -1F, -8F);
      Spore1.setTextureSize(64, 32);
      Spore1.mirror = true;
      setRotation(Spore1, 0.9666439F, -0.138092F, -0.448799F);
      Spore2 = new ModelRenderer(this, 16, 3);
      Spore2.addBox(-1F, 0F, -1F, 2, 2, 2);
      Spore2.setRotationPoint(4F, -1F, -2F);
      Spore2.setTextureSize(64, 32);
      Spore2.mirror = true;
      setRotation(Spore2, 0F, 0.5523679F, 0.5178449F);
      Spore3 = new ModelRenderer(this, 16, 3);
      Spore3.addBox(-1F, 0F, -1F, 2, 2, 2);
      Spore3.setRotationPoint(-6F, 1F, 3.577778F);
      Spore3.setTextureSize(64, 32);
      Spore3.mirror = true;
      setRotation(Spore3, 0F, 0.655371F, -0.8211945F);
      Spore4 = new ModelRenderer(this, 16, 3);
      Spore4.addBox(-1F, -1F, 0F, 2, 2, 2);
      Spore4.setRotationPoint(2.333333F, 8F, 7F);
      Spore4.setTextureSize(64, 32);
      Spore4.mirror = true;
      setRotation(Spore4, -1.407708F, -0.5463311F, -2.331906F);
  }

  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5,entity);
    Shape1.render(f5);
    Shape2.render(f5);
    Shape3.render(f5);
    Shape4.render(f5);
    Shape5.render(f5);
    Spore1.render(f5);
    Spore2.render(f5);
    Spore3.render(f5);
    Spore4.render(f5);
  }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5,entity);
  }

}
